BOOTSTRAP_CONFIG_JSON: false
USE_LOCAL_STORAGE: false
ENVIRONMENT: "Staging"
API_URL: "https://api.staging.monetr.dev"
SENTRY_DSN: https://3af2bafd7e774e96b4ca1f33b147875c@o579049.ingest.sentry.io/5735387
