site_name: monetr
site_description: Building an open source financial planning application.
site_url: !ENV [SITE_URL, 'http://monetr.local/documentation/']
repo_url: https://github.com/monetr/monetr
repo_name: GitHub
edit_uri: edit/main/docs/
copyright: Â© monetr LLC 2023
site_dir: build/site
watch:
  - docs
theme:
  name: material
  logo: img/logo192.png
  favicon: img/favicon.ico
  custom_dir: docs/custom/overrides
  features:
    - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra:
  homepage: https://monetr.app
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/monetr
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/monetr
    - icon: fontawesome/brands/discord
      link: https://discord.gg/68wTCXrhuq
extra_css:
  - stylesheets/extra.css
nav:
  - Home:
    - README.md
    - Contact: contact.md
  - Help:
      - help/index.md
      - Onboarding: help/onboarding.md
      - Funding Schedules:
          - help/funding_schedules/index.md
          - Adding A Funding Schedule: help/funding_schedules/adding.md
      - Links:
          - help/links/index.md
          - Link Statuses: help/links/link_statuses.md
      - Bank Accounts:
          - help/bank_accounts/index.md
          - Removing Links: help/bank_accounts/removing.md
      - Expenses:
          - help/expenses/index.md
      - Self-Hosting:
          - help/self_hosting/index.md
          - Command Line: help/self_hosting/command_line.md
  - Contributing:
      - developing/index.md
      - Code Of Conduct: developing/CODE_OF_CONDUCT.md
      - Documentation: developing/documentation.md
      - Developing:
          - Local Development: developing/local.md
          - Credentials: developing/credentials.md
          - GitHub Actions: developing/github_actions.md
      - API:
          - Resources:
              - developing/api/resources/index.md
              - Account Settings: developing/api/resources/account_settings.md
              - Authentication: developing/api/resources/authentication.md
              - Bank Accounts: developing/api/resources/bank_accounts.md
              - Funding Schedules: developing/api/resources/funding_schedules.md
              - Institutions: developing/api/resources/institutions.md
              - Links: developing/api/resources/links.md
              - Plaid Links: developing/api/resources/plaid_links.md
              - Spending: developing/api/resources/spending.md
              - Transactions: developing/api/resources/transactions.md
              - User: developing/api/resources/user.md

plugins:
  - search
  #  - section-index
  - render_swagger

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
