replicaCount: 2

image:
  repository: gcr.io/dogfood-326023/github.com/monetr/monetr
  pullPolicy: Always
  tag: "" # Will be overwritten with the SHA for the commit of this deploy

imagePullSecrets: [ ]

podAnnotations:
  monetr.dev/branch: "" # Branch of the deployment will be put here
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9000'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.monetr.dog
      paths:
        - path: /
  tls:
    - secretName: api-monetr-dog-tls
      hosts:
        - api.monetr.dog

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

disruption:
  enabled: false
  maxUnavailable: 1
  minAvailable: 1

api:
  name: monetr (dog)
  customEnv:
    - name: MONETR_ENVIRONMENT
      value: "dog"
    - name: MONETR_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: postgres-rest-api-secret
    - name: MONETR_PG_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: postgres-rest-api-secret
    - name: MONETR_JWT_LOGIN_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_JWT_LOGIN_SECRET
          name: rest-api-config-secrets
    - name: MONETR_JWT_REGISTRATION_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_JWT_REGISTRATION_SECRET
          name: rest-api-config-secrets
    - name: MONETR_CAPTCHA_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_CAPTCHA_PUBLIC_KEY
          name: rest-api-config-secrets
    - name: MONETR_CAPTCHA_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_CAPTCHA_PRIVATE_KEY
          name: rest-api-config-secrets
    - name: MONETR_PLAID_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: MONETR_PLAID_CLIENT_ID
          name: rest-api-config-secrets
    - name: MONETR_PLAID_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_PLAID_CLIENT_SECRET
          name: rest-api-config-secrets
    - name: MONETR_SENTRY_DSN
      valueFrom:
        secretKeyRef:
          key: MONETR_SENTRY_DSN
          name: monetr-dog-sentry
    - name: MONETR_STRIPE_API_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_STRIPE_API_KEY
          name: monetr-dog-stripe
    - name: MONETR_STRIPE_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_STRIPE_PUBLIC_KEY
          name: monetr-dog-stripe
    - name: MONETR_STRIPE_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_STRIPE_WEBHOOK_SECRET
          name: monetr-dog-stripe
  uiDomainName: my.monetr.dog
  apiDomainName: api.monetr.dog
  allowSignUp: true
  beta:
    enableBetaCodes: true
  postgreSql:
    address: postgres.google.dog.monetr.in
    port: 5432
    database: monetr
  email:
    enabled: false
    domain: monetr.dog
  sendGrid:
    enabled: false
    apiKey: ""
    templates:
      verifyEmailTemplate: ""
      forgotPasswordTemplate: ""
  reCaptcha:
    enabled: true
    verifyLogin: true
    verifyRegister: true
  plaid:
    environment: "https://development.plaid.com"
    enableReturningUserExperience: true
    webhooksEnabled: true
    webhooksDomain: api.monetr.dog
    oauthDomain: ui.monetr.dog
  cors:
    allowedOrigins:
      - "https://monetr.dog"
    debug: false
  redis:
    enabled: true
    address: redis.redis.kluster.monetr.in
    port: 6379
  logging:
    level: debug
  sentry:
    enabled: true
    sampleRate: 1.0
    traceSampleRate: 1.0
  stripe:
    enabled: true
    webhooksEnabled: true # Still working on this for now.
    webhooksDomain: https://api.monetr.dog
    billingEnabled: true
    initialPlan:
      stripePriceId: price_1JGYV0I4uGGnwpgw3kkur7ze
      features:
        - ManualBudgeting
        - LinkedBudgeting
