replicaCount: 2

image:
  repository: containers.monetr.dev/rest-api
  pullPolicy: Always
  tag: "" # Will be overwritten with the SHA for the commit of this deploy

imagePullSecrets:
  - name: containers.monetr.dev

podAnnotations:
  monetr.dev/branch: "" # Branch of the deployment will be put here
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9000'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.acceptance.monetr.dev
      paths:
        - path: /
  tls:
    - secretName: api-acceptance-monetr-dev-tls
      hosts:
        - api.acceptance.monetr.dev

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector:
  kubernetes.io/arch: amd64

api:
  name: monetr (acceptance)
  customEnv:
    - name: MONETR_ENVIRONMENT
      value: "acceptance"
    - name: MONETR_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: newfoundland-rest-api-secret
    - name: MONETR_PG_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: newfoundland-rest-api-secret
    - name: MONETR_JWT_LOGIN_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_JWT_LOGIN_SECRET
          name: rest-api-config-secrets
    - name: MONETR_JWT_REGISTRATION_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_JWT_REGISTRATION_SECRET
          name: rest-api-config-secrets
    - name: MONETR_CAPTCHA_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_CAPTCHA_PUBLIC_KEY
          name: rest-api-config-secrets
    - name: MONETR_CAPTCHA_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_CAPTCHA_PRIVATE_KEY
          name: rest-api-config-secrets
    - name: MONETR_PLAID_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: MONETR_PLAID_CLIENT_ID
          name: rest-api-config-secrets
    - name: MONETR_PLAID_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_PLAID_CLIENT_SECRET
          name: rest-api-config-secrets
    - name: MONETR_SENTRY_DSN
      valueFrom:
        secretKeyRef:
          key: MONETR_SENTRY_DSN
          name: monetr-acceptance-sentry
    - name: MONETR_STRIPE_API_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_STRIPE_API_KEY
          name: monetr-acceptance-stripe
    - name: MONETR_STRIPE_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_STRIPE_PUBLIC_KEY
          name: monetr-acceptance-stripe
    - name: MONETR_STRIPE_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_STRIPE_WEBHOOK_SECRET
          name: monetr-acceptance-stripe
  uiDomainName: acceptance.monetr.dev
  apiDomainName: api.acceptance.monetr.dev
  allowSignUp: true
  enableWebhooks: false # Will be deprecated soon.
  beta:
    enableBetaCodes: true
  postgreSql:
    address: newfoundland.monetr-acceptance.svc.cluster.local
    port: 5432
    database: monetr
  email:
    enabled: false
    domain: acceptance.monetr.dev
  sendGrid:
    enabled: false
    apiKey: ""
    templates:
      verifyEmailTemplate: ""
      forgotPasswordTemplate: ""
  reCaptcha:
    enabled: true
    verifyLogin: true
    verifyRegister: true
  plaid:
    environment: "https://development.plaid.com"
    enableReturningUserExperience: true
    webhooksEnabled: true
    webhooksDomain: api.acceptance.monetr.dev
    oauthDomain: acceptance.monetr.dev
  cors:
    allowedOrigins:
      - "https://acceptance.monetr.dev"
    debug: false
  redis:
    enabled: true
    address: redis.monetr-acceptance.svc.cluster.local
    port: 6379
  logging:
    level: debug
  sentry:
    enabled: true
    sampleRate: 1.0
    traceSampleRate: 1.0
  stripe:
    enabled: true
    webhooksEnabled: true # Still working on this for now.
    webhooksDomain: https://api.acceptance.monetr.dev
    billingEnabled: true
    initialPlan:
      stripePriceId: price_1JGYV0I4uGGnwpgw3kkur7ze
      features:
        - ManualBudgeting
        - LinkedBudgeting
