replicaCount: 1

image:
  repository: containers.monetr.dev/rest-api
  pullPolicy: always
  tag: "" # Will be overwritten with the SHA for the commit of this deploy

imagePullSecrets:
  - name: containers.monetr.dev

podAnnotations:
  monetr.dev/branch: "" # Branch of the deployment will be put here

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.staging.monetr.dev
      paths:
        - path: /
  tls:
    - secretName: api-staging-monetr-dev-tls
      hosts:
        - api.staging.monetr.dev

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  kubernetes.io/arch: amd64

api:
  name: monetr (staging)
  uiDomainName: app.staging.monetr.dev
  apiDomainName: api.staging.monetr.dev
  allowSignUp: true
  enableWebhooks: true
  jwt:
    loginJwtSecret: ""
    registrationJwtSecret: ""
  postgreSql:
    address: alsatian.monetr-staging.svc.cluster.local
    port: 5432
    username: monetr-api
    password: ""
    database: monetr
  smtp:
    enabled: false
  reCaptcha:
    enabled: true
    publicKey: ""
    privateKey: ""
  plaid:
    clientId: ""
    clientSecret: ""
    environment: "https://sandbox.plaid.com"
  cors:
    allowedOrigins:
      - "app.staging.monetr.dev"
    debug: true
  redis:
    enabled: true
    address: redis-main.monetr-staging.svc.cluster.local
    port: 6379
  logging:
    level: trace
