replicaCount: 2

image:
  repository: containers.monetr.dev/rest-api
  pullPolicy: Always
  tag: "" # Will be overwritten with the SHA for the commit of this deploy

imagePullSecrets:
  - name: containers.monetr.dev

podAnnotations:
  monetr.dev/branch: "" # Branch of the deployment will be put here

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.staging.monetr.dev
      paths:
        - path: /
  tls:
    - secretName: api-staging-monetr-dev-tls
      hosts:
        - api.staging.monetr.dev

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  kubernetes.io/arch: amd64

api:
  name: monetr (staging)
  customEnv:
    - name: MONETR_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: alsatian-rest-api-secret
    - name: MONETR_PG_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: alsatian-rest-api-secret
    - name: MONETR_JWT_LOGIN_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_JWT_LOGIN_SECRET
          name: rest-api-config-secrets
    - name: MONETR_JWT_REGISTRATION_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_JWT_REGISTRATION_SECRET
          name: rest-api-config-secrets
    - name: MONETR_CAPTCHA_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_CAPTCHA_PUBLIC_KEY
          name: rest-api-config-secrets
    - name: MONETR_CAPTCHA_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          key: MONETR_CAPTCHA_PRIVATE_KEY
          name: rest-api-config-secrets
    - name: MONETR_PLAID_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: MONETR_PLAID_CLIENT_ID
          name: rest-api-config-secrets
    - name: MONETR_PLAID_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: MONETR_PLAID_CLIENT_SECRET
          name: rest-api-config-secrets
  uiDomainName: app.staging.monetr.dev
  apiDomainName: api.staging.monetr.dev
  allowSignUp: true
  enableWebhooks: false
  postgreSql:
    address: alsatian.monetr-staging.svc.cluster.local
    port: 5432
    database: monetr
  smtp:
    enabled: false
  reCaptcha:
    enabled: true
  plaid:
    environment: "https://sandbox.plaid.com"
  cors:
    allowedOrigins:
      - "https://app.staging.monetr.dev"
    debug: true
  redis:
    enabled: true
    address: redis.monetr-staging.svc.cluster.local
    port: 6379
  logging:
    level: trace
